name = "benchmarking"
uuid = "f25d0ed0-23b1-4af7-b2c2-13aad3b970cb"
authors = ["Facundo Sosa-Rey <facundo.sosarey@gmail.com>"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
