name: CI-Thunderhead
on:
  - push
  - pull_request
jobs:
    build:
      runs-on: thunderhead
      steps:
        - uses: actions/checkout@v4
        - uses: julia-actions/setup-julia@latest
          with:
            version: '1.9.0'
        - name: Install dependencies
          run: >
            julia --project=. -e 
            'using Pkg;
             Pkg.instantiate()'
        - name: Build
          run: julia --project=. -e 
            include("tutorials/run_tutorials.jl");'
  