name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.6.7"
        os:
          - ubuntu-latest
          - macOS-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
          SNOWFLAKE_ID: ${{secrets.SNOWFLAKE_ID}}
          SNOWFLAKE_TOKEN: ${{secrets.SNOWFLAKE_TOKEN}}
          SNOWFLAKE_HOST: ${{secrets.SNOWFLAKE_HOST}}
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      
      - name: Build Snowflake
        run: >
          julia --project=. -e 
          'using Pkg;
          Pkg.develop(PackageSpec(path=pwd())); 
          Pkg.instantiate()'
      
      - name: Test Snowflake
        uses: julia-actions/julia-runtest@v1

      - name: Build SnowflakePlots
        run: >
          julia --project=SnowflakePlots.jl -e 
          'using Pkg;
          Pkg.develop(PackageSpec(path=pwd() * "/SnowflakePlots.jl")); 
          Pkg.develop(PackageSpec(path=pwd())); 
          Pkg.instantiate()'
      
      - name: Test SnowflakePlots
        uses: julia-actions/julia-runtest@v1
        with:
          project: 'SnowflakePlots.jl'
        env:
          SNOWFLAKE_ID: ${{secrets.SNOWFLAKE_ID}}
          SNOWFLAKE_TOKEN: ${{secrets.SNOWFLAKE_TOKEN}}
          SNOWFLAKE_HOST: ${{secrets.SNOWFLAKE_HOST}}

      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: src/core,SnowflakePlots.jl/src
      - uses: codecov/codecov-action@v2
        with:
          files: lcov.info
