name: Test Documentation
on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6.7'
      - name: Install dependencies
        run: >
          julia --project=docs/ -e 
          'using Pkg;
          Pkg.Registry.rm("General");
          Pkg.develop(PackageSpec(path=pwd())); 
          Pkg.develop(PackageSpec(path=pwd() * "/SnowflakePlots.jl")); 
          Pkg.instantiate()'
      - name: Build
        run: julia --project=docs/ docs/make.jl
